name: Pylint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.API_KEY }}
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
    strategy:
      matrix:
        python-version: ["3.11.9"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Code with Pylint
        run: |
          pylint website --fail-under=9 website

      - name: Run tests with Pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov=website --cov-report=term-missing -v
